# Generated by Django 3.2 on 2021-04-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Allegies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kcal', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Calories per serving (kcal)')),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Sodium contents per serving (mg)')),
                ('saturated_fat_g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Saturated fat contents per serving(g)')),
                ('sugars_g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Sugar contents per serving (g)')),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Protein contents per serving (g)')),
                ('caffeine_mg', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Caffeine contents per sercing (mg)')),
                ('size_ml', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Size per serving (ml)')),
                ('size_ounce', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Size per serving (oz)')),
            ],
            options={
                'verbose_name_plural': 'Nutritions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(max_length=45)),
                ('english_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductAllegy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allegy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'ProductAllegies',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allegies',
            field=models.ManyToManyField(blank=True, through='products.ProductAllegy', to='products.Allegy'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nutrition'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.menu'),
        ),
    ]
